version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: user 
      RABBITMQ_DEFAULT_PASS: password 
  
  java-app:
    image: openjdk:8-jre-alpine
    container_name: java-app
    build:  
      context: .  
      dockerfile: Dockerfile  
    depends_on:
      - rabbitmq
    command: ["java", "-jar", "app.jar"]  
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"